### PR TITLE
Added Dueling DQN

### PR DESCRIPTION
**Pull request by lockwo**
I saw there was a need for the dueling DQN on the "Remaining issues & research questions" section, and I figured it would be a good first contribution. I am working on getting access to more compute right now, so I just have a few comparisons. Outside of the neural network code, the rest remains the same as the DQN. 

Cartpole: Orange is dueling, green is dqn
cartpole_comp
Lunar Lander: pink is dueling, blue is dqn
charts_episodic_return (2)
Breakout: both are dueling (two separate runs)
charts_episodic_return (3)

### CODE REVIEW

**Review by vwxyzjn — CHANGES_REQUESTED** [review]
Would you mind incorporating these changes? Also please run `poetry run pre-commit run  --all-files` to auto-format the files.

Everything else looks good to me! Great work!

**Comment by lockwo** [comment]
Ok, I resolved the three comments (changing the wandb project and entity, and the name for the intermediate nn state). I also ran the formatting pre-commit.

**Comment by lockwo** [comment]
I will run some new tracked experiments shortly (over the next few days). Should they be new ones, or can I sync the existing runs to the project?

**Comment by vwxyzjn** [comment]
>Ok, I resolved the three comments (changing the wandb project and entity, and the name for the intermediate nn state). I also ran the formatting pre-commit.

Thank you very much!

> I will run some new tracked experiments shortly (over the next few days). Should they be new ones, or can I sync the existing runs to the project?

Sure, if you can sync the existing run into the project that would save time!

**Review by vwxyzjn — APPROVED** [review]

**Comment by lockwo** [comment]
Added cartpole and lunarlander runs to project. Running breakout run now.

**Comment by vwxyzjn** [comment]
Awesome https://wandb.ai/vwxyzjn/vectorized-value-methods/reports/DDQN--VmlldzoxNTAwNDkw tracks this benchmark now

**Comment by vwxyzjn** [comment]
Oh btw do you have a GPU by any chance? Atari experiments may take a long time with CPU :)

**Comment by vwxyzjn** [comment]
The learning curve already makes sense. Merging now. Thank you @lockwo so much

D451F22D-AED9-4627-AFEA-6ABEA7A2A409

**Pull request merged**
